export type ExceptionCode =
  | 'CATEGORY_NOT_FOUND'
  | 'INTERNAL_SERVER_ERROR'
  | 'INVALID_DATA'
  | 'INVALID_TOKEN'
  | 'INCORRECT_PASSWORD'
  | 'PRODUCT_NOT_FOUND'
  | 'PARAMS_NOT_FOUND'
  | 'USER_EXISTS'
  | 'USER_NOT_FOUND';
